### ISSUE TITLE
Add --with-pa to Dockerfile

### ISSUE THREAD

**Issue by synclpz** [mikebrady/shairport-sync-docker#1]
Why PulseAudio is not enabled in dockerized version?

**Comment by mikebrady** [comment]
Good point. I’ll do it over the next few days.

**Comment by synclpz** [comment]
I forked your repo and did my own image with specific setup, especially removing d-bus and avahi daemons from container and allowing shairport-sync to connect to host's avahi via `--volume /var/run/dbus/:/var/run/dbus/ `, you could check this at https://github.com/synclpz/docker-shairport-sync/blob/master/start.sh

**Comment by mikebrady** [comment]
Thanks for that. I'll add the `--with-pa stuff` shortly. 

Your approach is very nice, and I'm learning something from it, particularly about the advantages of Docker.

However, the image is really aimed at users who just want to get Shairport Sync working with a minimum of effort, so I'll leave in the `avahi` and `dbus` services in place. Experts can easily refrain from enabling them.

**Comment by mikebrady** [comment]
I'll do this, promise!

**Comment by mikebrady** [comment]
So, I've done this, but I think I should leave the pulseaudio library out of the runtime image. What do you think -- an interested user can add it themselves, no?

I really do not want to include any pulseaudio stuff if I can avoid it, but perhaps, by the same logic, I should also remove the mosquitto lib from the runtime?

**Comment by rohmishra** [comment]
perhaps we could create a separate pa image that uses pa by default and includes pa OR require connecting to a pa container/host instance.

**Comment by mikebrady** [comment]
Thanks for the suggestion. At the moment, I think this hits the spot for generality. If you were to publish that yourself, it would be great.
