### ISSUE TITLE
No logs in default output

### ISSUE THREAD

**Issue by rkachowski** [mikebrady/shairport-sync-docker#14]
I'm running the image `96101ff88ff1` on raspberry pi and I can't seem to see any output in the logs. I'm running the image as follows.

`docker run --net host -v /home/pi/shairport-sync.conf:/etc/shairport-sync.conf -v /home/pi/music/shairport:/home/shairport-sync/shairport  mikebrady/shairport-sync`

Where `/home/pi/music/shairport` is a named pipe and the below config file is mounted into the container.

```
general =
{
	name = "Kitchen Speakers";
	output_backend = "pipe";
	log_verbosity = 3; // "0" means no debug verbosity, "3" is most verbose.
};

sessioncontrol =
{
	allow_session_interruption = "yes"; 
	session_timeout = 20; 
};

pipe =
{
  name = "/home/shairport-sync/shairport";
  mixer_control_name = "PCM";
  audio_backend_buffer_desired_length = 48000; /
};
```

Audio works fine and I can connect and play, but I can't see any log output either directly from the command (running in non daemon mode) or from `docker logs`. For monitoring and debug purposes I'd like to be able to view the logs from journalctl which expects the logs to be written to stdout.

**Comment by mikebrady** [comment]
Thanks for the post. AFAIK, this is something to do with the settings or Docker. There are some settings (which I'm afraid I have forgotten) for getting the logs. However, there is also a setting in the configuration file of Shairport Sync -- the `log_output_to` setting accepts a full path name to a file in which the log will be stored. You should not set a log verbosity of 3 initially; I suggest 1.

**Comment by rkachowski** [comment]
Thanks for getting back. I set log verbosity to the highest to ensure that the output wasn't empty due to the log level excluding all entries.

After looking through the code it seems that the config needs to include a `diagnostics` object with the value

```
diagnostics =
{
        log_output_to = "stdout";
};
```

once this is there it seems to work fine.
