### ISSUE TITLE
Error pulling image with tag 'latest'.

### ISSUE THREAD

**Issue by charlesomer** [mikebrady/shairport-sync-docker#2]
When no docker image tag is specified like in the readme, it defaults to 'latest' but this presents the following error:
`ERROR: manifest for mikebrady/shairport-sync:latest not found: manifest unknown: manifest unknown`
Manually setting a tag (e.g. 3.3.6) does work.

**Comment by mikebrady** [comment]
Thanks for the note. Yeah, I seem to have broken the workflow that tagged the latest. I’ll have to look at it again.

**Comment by charlesomer** [comment]
Okay thank you :)

**Comment by charlesomer** [comment]
Quick question, how do I view the logs in the docker container? I was expecting to see them in /var/logs but they don't seem to be there?
I'm trying to pipe audio to forked-daapd and looking for error messages since it's not working at the moment

(Never mind, it was a permissions error)

**Comment by mikebrady** [comment]
Should be a 'latest' tagged build there now.

**Comment by charlesomer** [comment]
Great it seems to be working now, thank you!
