### ISSUE TITLE
On Raspberry Pi 4 not working

### ISSUE THREAD

**Issue by Vannixxo** [mikebrady/shairport-sync-docker#3]
Hello! I really hoped it would work by simply running the container, but it is not.
It didn't work before latest raspbian update, and it isn't working now after updating and having pulse audio replaced ALSA.
I tried adding `--with-pa` but the container restarts and doesn't work

**Comment by mikebrady** [comment]
Thanks for the post. Shairport Sync is not yet built to support PulseAudio. The `--with-pa` is a build option when you are configuring the compilation of Shairport Sync -- it is not a Docker option or a runtime option for Shairport Sync.

The latest Docker image is working fine to an ALSA backend on a stock Raspberry Pi 3B+ running an up-to-date Raspberry OS: 
```
5.4.79-v7+ #1373 SMP Mon Nov 23 13:22:33 GMT 2020 armv7l GNU/Linux
```
