### ISSUE TITLE
Trying to setup shairport docker to start at boot using systemd

### ISSUE THREAD

**Issue by yeralin** [mikebrady/shairport-sync-docker#5]
Hi,

System: `Linux raspberrypi 5.4.72-v7+ #1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux`

The docker image is running perfectly on my raspberry. Now I wanted to start it at boot, here is my systemd service file:
```
[Unit]
Description=Shairport Container
After=docker.service
After=avahi-daemon.service
Requires=docker.service
Requires=avahi-daemon.service

[Service]
User=<uid>
Group=<gid>
Restart=always
ExecStartPre=-/usr/bin/docker stop shairport
ExecStart=/usr/bin/docker start -a shairport
ExecStop=/usr/bin/docker stop shairport

[Install]
WantedBy=multi-user.target
```

But after reboot, I get `Process 12 died: No such process; trying to remove PID file. (/run/avahi-daemon//pid)` in `shairport` docker logs. The only way to fix it is to `docker restart shairport`.

**Comment by mikebrady** [comment]
Thanks for the post. I don't think that is how you set a docker image to start on boot -- see the Readme at https://hub.docker.com/repository/docker/mikebrady/shairport-sync.

**Comment by yeralin** [comment]
Right, that service is for starting the **existing** docker image at boot.
The original command was:
```
docker run -d \
--restart unless-stopped \
--name shairport \
--net host \
--device /dev/snd \
mikebrady/shairport-sync -- \
-d hw:1
```

**Comment by mikebrady** [comment]
Thanks. That command should, in fact, cause the existing image to be launched automatically on boot. It does for me.

**Comment by yeralin** [comment]
Right, but when I reboot my raspberry, I get `Process 12 died: No such process; trying to remove PID file. (/run/avahi-daemon//pid)`, and I have to execute `systemctl restart shairport`

Seems like it gets launched too early at boot, and something is not up yet for it to work properly. 

But then I have `After=avahi-daemon.service`

**Comment by mikebrady** [comment]
Just circling back to this. You don't need to do anything at all to the host machine's `systemd` service file to get Docker to start the image after boot. If you have made changes to the `systemd` service file, then I'd suggest you undo them.
